### ISSUE TITLE
PCB size used for Elecrow fab order

### ISSUE THREAD

**Issue by pslogic** [Ryzee119/GBA_Emulator-by-Ryzee119-#1]
Hi,

Great project... thanks for sharing!

Can you advise what PCB size you used in your order to Elecrow? Did you choose `10cm Max x 16cm Max + $32.50`?

**Comment by Ryzee119** [comment]
Hi,
Yes. 10cm x 16cm max

**Comment by pslogic** [comment]
Thanks! 👍
