### ISSUE TITLE
Question regarding to interfacing SPI screen to raspberry zero

### ISSUE THREAD

**Issue by justauser42** [Ryzee119/GBA_Emulator-by-Ryzee119-#10]
Great work!

I am also working on a GBA mod... I have some basic experience with hooking up a 2.2" ili9341 SPI TFT Screen to the Zero using the connection scheme below:

Display--------Raspberry Pi
BL--------------pin 12 (GPIO 18)
SCK------------pin 23 (GPIO 11)	
MISO----------pin 21 (GPIO 9)
MOSI----------pin 19 (GPIO 10)
CS--------------pin 24 (GPIO 8)
RST------------pin 22 (GPIO 25)
D/C-------------pin 18 (GPIO 24)
VIN-------------pin 17 (3.3v)
GND-----------pin 20 (GND)

Is there a datasheet out there for the TFT you used? 

For example (I only have a basic knowledge on electronics. ), I noticed that for this TFT you specifically use 2.8V for VIN (with a dedicated regulator) and the TFT_LED also has a specific amplifier (this is the backlight connection I assume?).

Last question. How is the viewing angle of the 3.2" TFT you used? The 2.2" has a very narrow viewing range.

Thanks.

**Comment by Ryzee119** [comment]
See TFT datasheet: https://www.itead.cc/wiki/images/5/52/H24TM84A-spec.pdf

Viewing angle is not the best, fine for handheld gaming in my opinion. The above datasheet has some information about viewing angle.

Yes the 'amplifier' is for the backlight. It's more of a current buffer so the rasp pi IO is not driving the backlight on its own. It is PWM driven for brightness.

Good luck!
