### ISSUE TITLE
Recommendation for welding?

### ISSUE THREAD

**Issue by flug** [Ryzee119/GBA_Emulator-by-Ryzee119-#5]
Hello
I went on a similar system before falling on your project. So your project seems to be significantly more reliable than what I was doing. However I wanted to see if you have recommendations for the soldering iron to the components and Tin? What might help the other diy, who may not have adequate material and avoid to enter a building that may be abortion.  :neckbeard:

**Comment by Ryzee119** [comment]
Im using a Hakko FX-888D soldering station, with 60/40 multicore leaded solder. Using thin solder (less than 0.8mm diameter) for surface mount stuff. I just happen to use Multicore 389261.

I also recommend some solder flux which will make your life alot easier. I use a Milticore brand Flux Pen.

Some good non-magnetic tweezers will help placing surface point parts.

Get some soldering wick of a good reputable brand which contains flux! Dont get the cheap stuff on ebay.
