### ISSUE TITLE
Bourns Inc. PVZ3A473C01R00  Obsolete

### ISSUE THREAD

**Issue by flug** [Ryzee119/GBA_Emulator-by-Ryzee119-#6]
hi, this product [Bourns Inc. PVZ3A473C01R00](https://www.digikey.com.au/product-detail/en/bourns-inc/PVZ3A473C01R00/490-7795-1-ND/4358063) is obsolete so unavailable. can we replace it with what?

**Comment by flug** [comment]
ping @Ryzee119  :D

**Comment by Ryzee119** [comment]
Hey mate,
Sorry didn't see this. Resistance value isn't critical, so just use something like:
https://www.digikey.com.au/product-detail/en/bourns-inc/TC33X-2-103E/TC33X-103ECT-ND/612911

Cheers

**Comment by flug** [comment]
Hey 
Thank you so much for coming back :+1:
